
service: techdays2-hackathon

provider:
  name: aws
  runtime: nodejs12.x
  
resources:
  Resources:
    Teams:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: Teams
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UserStatus:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: UserStatus
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: S
          - AttributeName: statusKey
            AttributeType: S
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
          - AttributeName: statusKey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST


functions:
  listTeams:
    handler: listTeams/handler.main
    events:
      - http:
          path: teams
          method: get
          
  getTeam:
    handler: getTeam/handler.main
    events:
      - http:
          path: team/{teamId}
          method: get
          request:
            parameters:
              paths:
                teamId: true
  
  getStatus:
    handler: getStatus/handler.main
    events:
      - http:
          path: team/{teamId}/status/{userId}
          method: get
          request:
            parameters:
              paths:
                teamId: true
                userId: true
  
  updateStatus:
    handler: updateStatus/handler.main
    events:
      - http:
          path: team/{teamId}/status/{userId}
          method: post
          request:
            parameters:
              paths:
                teamId: true
                userId: true